
services:
  cpp-gmsh:
    build:
      context: ../                # Указываем контекст как родительскую папку
      dockerfile: docker/Dockerfile  # Путь к Dockerfile, который в папке docker
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../src:/src                # Монтируем src из родительской директории в контейнер
    working_dir: /src               # Указываем рабочую директорию в контейнере
    tty: true                       # Для интерактивной работы с контейнером (если нужно)
    network_mode: "host"
